#!/usr/bin/env bash
# compare-charts.sh — measure how identical two generated Helm charts are.
#
# Determinism check for the helm-chart-creator skill: run the skill twice with
# the SAME interview answers, then compare the two output chart directories.
# Reports file-set similarity (Jaccard) + line-level similarity, and exits 0
# only if overall similarity >= THRESHOLD (default 95%).
#
# Usage:  ./compare-charts.sh <chart-dir-A> <chart-dir-B> [threshold_percent]
#
# Notes:
#   - Compares files by relative path under each chart dir.
#   - README.md is generated by helm-docs and is deterministic given the same
#     values; it is included. Pass a 4th arg to exclude globs if desired.

# No `-e`: diff/cmp returning non-zero (files differ) is expected, not fatal.
set -uo pipefail

A="${1:?usage: compare-charts.sh <dirA> <dirB> [threshold]}"
B="${2:?usage: compare-charts.sh <dirA> <dirB> [threshold]}"
THRESHOLD="${3:-95}"

[[ -d "$A" ]] || { echo "ERROR: not a directory: $A" >&2; exit 2; }
[[ -d "$B" ]] || { echo "ERROR: not a directory: $B" >&2; exit 2; }

# Relative file lists (sorted), ignoring VCS noise. Portable to bash 3.2 (macOS).
list_files() { (cd "$1" && find . -type f -not -path './.git/*' | sed 's|^\./||' | sort); }

TMP_A=$(mktemp); TMP_B=$(mktemp)
trap 'rm -f "$TMP_A" "$TMP_B"' EXIT
list_files "$A" > "$TMP_A"
list_files "$B" > "$TMP_B"

# --- File-set Jaccard ---------------------------------------------------------
only_a=$(comm -23 "$TMP_A" "$TMP_B" || true)
only_b=$(comm -13 "$TMP_A" "$TMP_B" || true)
common=$(comm -12 "$TMP_A" "$TMP_B" || true)

n_only_a=$([[ -z "$only_a" ]] && echo 0 || printf '%s\n' "$only_a" | grep -c .)
n_only_b=$([[ -z "$only_b" ]] && echo 0 || printf '%s\n' "$only_b" | grep -c .)
n_common=$([[ -z "$common" ]] && echo 0 || printf '%s\n' "$common" | grep -c .)
n_union=$(( n_common + n_only_a + n_only_b ))

# --- Line-level similarity over common files ---------------------------------
total_common_lines=0
total_max_lines=0
declare -a per_file_report=()

count_lines() { wc -l < "$1" | tr -d ' '; }

while IFS= read -r f; do
  [[ -z "$f" ]] && continue
  fa="$A/$f"; fb="$B/$f"
  la=$(count_lines "$fa"); lb=$(count_lines "$fb")
  maxl=$(( la > lb ? la : lb ))
  # Common lines via the LCS that `diff` computes. Portable: uses normal-format
  # diff (works on GNU and BSD/macOS), counting lines added on the B side (`>`).
  # common = lines(B) - addedOrChanged(B). No GNU-only --*-line-format flags.
  if cmp -s "$fa" "$fb"; then
    same="$maxl"
  else
    added=$(diff "$fa" "$fb" 2>/dev/null | grep -c '^>')
    same=$(( lb - added ))
    [[ "$same" -lt 0 ]] && same=0
  fi
  total_common_lines=$(( total_common_lines + same ))
  total_max_lines=$(( total_max_lines + maxl ))
  if [[ "$maxl" -gt 0 && "$same" -lt "$maxl" ]]; then
    pct=$(( same * 100 / maxl ))
    per_file_report+=("  ~ $f : ${pct}% (${same}/${maxl} lines)")
  fi
done <<< "$common"

# Files present in only one side count their lines as fully non-matching.
add_orphans() {
  local dir="$1"; shift
  local listvar="$1"
  while IFS= read -r f; do
    [[ -z "$f" ]] && continue
    l=$(count_lines "$dir/$f")
    total_max_lines=$(( total_max_lines + l ))
  done <<< "$listvar"
}
add_orphans "$A" "$only_a"
add_orphans "$B" "$only_b"

# --- Scores -------------------------------------------------------------------
if [[ "$n_union" -gt 0 ]]; then
  jaccard=$(( n_common * 100 / n_union ))
else
  jaccard=100
fi
if [[ "$total_max_lines" -gt 0 ]]; then
  line_sim=$(( total_common_lines * 100 / total_max_lines ))
else
  line_sim=100
fi
# Overall = mean of file-set and line similarity.
overall=$(( (jaccard + line_sim) / 2 ))

# --- Report -------------------------------------------------------------------
echo "=================================================="
echo " Helm chart determinism comparison"
echo "   A: $A"
echo "   B: $B"
echo "=================================================="
echo "File set:   common=$n_common  only-in-A=$n_only_a  only-in-B=$n_only_b  (Jaccard ${jaccard}%)"
[[ -n "$only_a" ]] && { echo "  files only in A:"; printf '    - %s\n' $only_a; }
[[ -n "$only_b" ]] && { echo "  files only in B:"; printf '    - %s\n' $only_b; }
echo "Line match: ${total_common_lines}/${total_max_lines} lines identical (${line_sim}%)"
if [[ "${#per_file_report[@]}" -gt 0 ]]; then
  echo "Files that differ:"
  printf '%s\n' "${per_file_report[@]}"
else
  echo "All common files are byte-identical."
fi
echo "--------------------------------------------------"
echo "OVERALL SIMILARITY: ${overall}%   (threshold ${THRESHOLD}%)"
echo "=================================================="

if [[ "$overall" -ge "$THRESHOLD" ]]; then
  echo "PASS ✅  deterministic within threshold"
  exit 0
else
  echo "FAIL ❌  output drifted beyond threshold"
  exit 1
fi
