apiVersion: v1
kind: Service
metadata:
  name: {{ include "CHARTNAME.fullname" . }}
  namespace: {{ include "CHARTNAME.namespace" . | quote }}
  labels: {{- include "CHARTNAME.labels" . | nindent 4 }}
  {{- if or .Values.service.annotations .Values.commonAnnotations }}
  annotations:
    {{- with .Values.commonAnnotations }}{{- toYaml . | nindent 4 }}{{- end }}
    {{- with .Values.service.annotations }}{{- toYaml . | nindent 4 }}{{- end }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  {{- if and .Values.service.clusterIP (eq .Values.service.type "ClusterIP") }}
  clusterIP: {{ .Values.service.clusterIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerIP }}
  loadBalancerIP: {{ .Values.service.loadBalancerIP }}
  {{- end }}
  {{- if and (eq .Values.service.type "LoadBalancer") .Values.service.loadBalancerSourceRanges }}
  loadBalancerSourceRanges: {{- toYaml .Values.service.loadBalancerSourceRanges | nindent 4 }}
  {{- end }}
  {{- if not (eq .Values.service.type "ClusterIP") }}
  externalTrafficPolicy: {{ .Values.service.externalTrafficPolicy | quote }}
  {{- end }}
  {{- with .Values.service.sessionAffinity }}
  sessionAffinity: {{ . }}
  {{- end }}
  ports:
    {{- range $name, $port := .Values.service.ports }}
    - name: {{ $name }}
      port: {{ $port }}
      targetPort: {{ $name }}
      protocol: TCP
      {{- if and (eq $.Values.service.type "NodePort") (index $.Values.service.nodePorts $name) }}
      nodePort: {{ index $.Values.service.nodePorts $name }}
      {{- end }}
    {{- end }}
    {{- if .Values.metrics.enabled }}
    - name: metrics
      port: {{ .Values.metrics.service.ports.metrics }}
      targetPort: metrics
      protocol: TCP
    {{- end }}
    {{- with .Values.service.extraPorts }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  selector: {{- include "CHARTNAME.selectorLabels" . | nindent 4 }}
